// Code generated by go-swagger; DO NOT EDIT.

package accessoidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateUIExtensionTokenOidcReader is a Reader for the CreateUIExtensionTokenOidc structure.
type CreateUIExtensionTokenOidcReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateUIExtensionTokenOidcReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateUIExtensionTokenOidcOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCreateUIExtensionTokenOidcForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateUIExtensionTokenOidcConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateUIExtensionTokenOidcInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateUIExtensionTokenOidcOK creates a CreateUIExtensionTokenOidcOK with default headers values
func NewCreateUIExtensionTokenOidcOK() *CreateUIExtensionTokenOidcOK {
	return &CreateUIExtensionTokenOidcOK{}
}

/*CreateUIExtensionTokenOidcOK handles this case with default header values.

successful operation
*/
type CreateUIExtensionTokenOidcOK struct {
	Payload string
}

func (o *CreateUIExtensionTokenOidcOK) Error() string {
	return fmt.Sprintf("[POST /access/oidc/ui-extension-token][%d] createUiExtensionTokenOidcOK  %+v", 200, o.Payload)
}

func (o *CreateUIExtensionTokenOidcOK) GetPayload() string {
	return o.Payload
}

func (o *CreateUIExtensionTokenOidcOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateUIExtensionTokenOidcForbidden creates a CreateUIExtensionTokenOidcForbidden with default headers values
func NewCreateUIExtensionTokenOidcForbidden() *CreateUIExtensionTokenOidcForbidden {
	return &CreateUIExtensionTokenOidcForbidden{}
}

/*CreateUIExtensionTokenOidcForbidden handles this case with default header values.

Client is not authorized to make this request.
*/
type CreateUIExtensionTokenOidcForbidden struct {
}

func (o *CreateUIExtensionTokenOidcForbidden) Error() string {
	return fmt.Sprintf("[POST /access/oidc/ui-extension-token][%d] createUiExtensionTokenOidcForbidden ", 403)
}

func (o *CreateUIExtensionTokenOidcForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateUIExtensionTokenOidcConflict creates a CreateUIExtensionTokenOidcConflict with default headers values
func NewCreateUIExtensionTokenOidcConflict() *CreateUIExtensionTokenOidcConflict {
	return &CreateUIExtensionTokenOidcConflict{}
}

/*CreateUIExtensionTokenOidcConflict handles this case with default header values.

Unable to create the download token because NiFi is not in the appropriate state. (i.e. may not have any tokens to grant or be configured to support username/password login)
*/
type CreateUIExtensionTokenOidcConflict struct {
}

func (o *CreateUIExtensionTokenOidcConflict) Error() string {
	return fmt.Sprintf("[POST /access/oidc/ui-extension-token][%d] createUiExtensionTokenOidcConflict ", 409)
}

func (o *CreateUIExtensionTokenOidcConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateUIExtensionTokenOidcInternalServerError creates a CreateUIExtensionTokenOidcInternalServerError with default headers values
func NewCreateUIExtensionTokenOidcInternalServerError() *CreateUIExtensionTokenOidcInternalServerError {
	return &CreateUIExtensionTokenOidcInternalServerError{}
}

/*CreateUIExtensionTokenOidcInternalServerError handles this case with default header values.

Unable to create download token because an unexpected error occurred.
*/
type CreateUIExtensionTokenOidcInternalServerError struct {
}

func (o *CreateUIExtensionTokenOidcInternalServerError) Error() string {
	return fmt.Sprintf("[POST /access/oidc/ui-extension-token][%d] createUiExtensionTokenOidcInternalServerError ", 500)
}

func (o *CreateUIExtensionTokenOidcInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
