// Code generated by go-swagger; DO NOT EDIT.

package accessoidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLoginConfigOidcParams creates a new GetLoginConfigOidcParams object
// with the default values initialized.
func NewGetLoginConfigOidcParams() *GetLoginConfigOidcParams {

	return &GetLoginConfigOidcParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLoginConfigOidcParamsWithTimeout creates a new GetLoginConfigOidcParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLoginConfigOidcParamsWithTimeout(timeout time.Duration) *GetLoginConfigOidcParams {

	return &GetLoginConfigOidcParams{

		timeout: timeout,
	}
}

// NewGetLoginConfigOidcParamsWithContext creates a new GetLoginConfigOidcParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLoginConfigOidcParamsWithContext(ctx context.Context) *GetLoginConfigOidcParams {

	return &GetLoginConfigOidcParams{

		Context: ctx,
	}
}

// NewGetLoginConfigOidcParamsWithHTTPClient creates a new GetLoginConfigOidcParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLoginConfigOidcParamsWithHTTPClient(client *http.Client) *GetLoginConfigOidcParams {

	return &GetLoginConfigOidcParams{
		HTTPClient: client,
	}
}

/*GetLoginConfigOidcParams contains all the parameters to send to the API endpoint
for the get login config oidc operation typically these are written to a http.Request
*/
type GetLoginConfigOidcParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get login config oidc params
func (o *GetLoginConfigOidcParams) WithTimeout(timeout time.Duration) *GetLoginConfigOidcParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get login config oidc params
func (o *GetLoginConfigOidcParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get login config oidc params
func (o *GetLoginConfigOidcParams) WithContext(ctx context.Context) *GetLoginConfigOidcParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get login config oidc params
func (o *GetLoginConfigOidcParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get login config oidc params
func (o *GetLoginConfigOidcParams) WithHTTPClient(client *http.Client) *GetLoginConfigOidcParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get login config oidc params
func (o *GetLoginConfigOidcParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLoginConfigOidcParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
