// Code generated by go-swagger; DO NOT EDIT.

package accessoidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// KnoxRequestOidcReader is a Reader for the KnoxRequestOidc structure.
type KnoxRequestOidcReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KnoxRequestOidcReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewKnoxRequestOidcDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewKnoxRequestOidcDefault creates a KnoxRequestOidcDefault with default headers values
func NewKnoxRequestOidcDefault(code int) *KnoxRequestOidcDefault {
	return &KnoxRequestOidcDefault{
		_statusCode: code,
	}
}

/*KnoxRequestOidcDefault handles this case with default header values.

successful operation
*/
type KnoxRequestOidcDefault struct {
	_statusCode int
}

// Code gets the status code for the knox request oidc default response
func (o *KnoxRequestOidcDefault) Code() int {
	return o._statusCode
}

func (o *KnoxRequestOidcDefault) Error() string {
	return fmt.Sprintf("[GET /access/oidc/knox/request][%d] knoxRequestOidc default ", o._statusCode)
}

func (o *KnoxRequestOidcDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
