// Code generated by go-swagger; DO NOT EDIT.

package accessoidc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// LogOutCompleteOidcReader is a Reader for the LogOutCompleteOidc structure.
type LogOutCompleteOidcReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LogOutCompleteOidcReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewLogOutCompleteOidcOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewLogOutCompleteOidcUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewLogOutCompleteOidcInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewLogOutCompleteOidcOK creates a LogOutCompleteOidcOK with default headers values
func NewLogOutCompleteOidcOK() *LogOutCompleteOidcOK {
	return &LogOutCompleteOidcOK{}
}

/*LogOutCompleteOidcOK handles this case with default header values.

User was logged out successfully.
*/
type LogOutCompleteOidcOK struct {
}

func (o *LogOutCompleteOidcOK) Error() string {
	return fmt.Sprintf("[GET /access/oidc/logout/complete][%d] logOutCompleteOidcOK ", 200)
}

func (o *LogOutCompleteOidcOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLogOutCompleteOidcUnauthorized creates a LogOutCompleteOidcUnauthorized with default headers values
func NewLogOutCompleteOidcUnauthorized() *LogOutCompleteOidcUnauthorized {
	return &LogOutCompleteOidcUnauthorized{}
}

/*LogOutCompleteOidcUnauthorized handles this case with default header values.

Authentication token provided was empty or not in the correct JWT format.
*/
type LogOutCompleteOidcUnauthorized struct {
}

func (o *LogOutCompleteOidcUnauthorized) Error() string {
	return fmt.Sprintf("[GET /access/oidc/logout/complete][%d] logOutCompleteOidcUnauthorized ", 401)
}

func (o *LogOutCompleteOidcUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewLogOutCompleteOidcInternalServerError creates a LogOutCompleteOidcInternalServerError with default headers values
func NewLogOutCompleteOidcInternalServerError() *LogOutCompleteOidcInternalServerError {
	return &LogOutCompleteOidcInternalServerError{}
}

/*LogOutCompleteOidcInternalServerError handles this case with default header values.

Client failed to log out.
*/
type LogOutCompleteOidcInternalServerError struct {
}

func (o *LogOutCompleteOidcInternalServerError) Error() string {
	return fmt.Sprintf("[GET /access/oidc/logout/complete][%d] logOutCompleteOidcInternalServerError ", 500)
}

func (o *LogOutCompleteOidcInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
