// Code generated by go-swagger; DO NOT EDIT.

package input_ports

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetInputPortParams creates a new GetInputPortParams object
// with the default values initialized.
func NewGetInputPortParams() *GetInputPortParams {
	var ()
	return &GetInputPortParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetInputPortParamsWithTimeout creates a new GetInputPortParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetInputPortParamsWithTimeout(timeout time.Duration) *GetInputPortParams {
	var ()
	return &GetInputPortParams{

		timeout: timeout,
	}
}

// NewGetInputPortParamsWithContext creates a new GetInputPortParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetInputPortParamsWithContext(ctx context.Context) *GetInputPortParams {
	var ()
	return &GetInputPortParams{

		Context: ctx,
	}
}

// NewGetInputPortParamsWithHTTPClient creates a new GetInputPortParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetInputPortParamsWithHTTPClient(client *http.Client) *GetInputPortParams {
	var ()
	return &GetInputPortParams{
		HTTPClient: client,
	}
}

/*GetInputPortParams contains all the parameters to send to the API endpoint
for the get input port operation typically these are written to a http.Request
*/
type GetInputPortParams struct {

	/*ID
	  The input port id.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get input port params
func (o *GetInputPortParams) WithTimeout(timeout time.Duration) *GetInputPortParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get input port params
func (o *GetInputPortParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get input port params
func (o *GetInputPortParams) WithContext(ctx context.Context) *GetInputPortParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get input port params
func (o *GetInputPortParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get input port params
func (o *GetInputPortParams) WithHTTPClient(client *http.Client) *GetInputPortParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get input port params
func (o *GetInputPortParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get input port params
func (o *GetInputPortParams) WithID(id string) *GetInputPortParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get input port params
func (o *GetInputPortParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetInputPortParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
