// Code generated by go-swagger; DO NOT EDIT.

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/bjornm82/go-swagger-nifi/models"
)

// NewCreateBulletinParams creates a new CreateBulletinParams object
// with the default values initialized.
func NewCreateBulletinParams() *CreateBulletinParams {
	var ()
	return &CreateBulletinParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBulletinParamsWithTimeout creates a new CreateBulletinParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateBulletinParamsWithTimeout(timeout time.Duration) *CreateBulletinParams {
	var ()
	return &CreateBulletinParams{

		timeout: timeout,
	}
}

// NewCreateBulletinParamsWithContext creates a new CreateBulletinParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateBulletinParamsWithContext(ctx context.Context) *CreateBulletinParams {
	var ()
	return &CreateBulletinParams{

		Context: ctx,
	}
}

// NewCreateBulletinParamsWithHTTPClient creates a new CreateBulletinParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateBulletinParamsWithHTTPClient(client *http.Client) *CreateBulletinParams {
	var ()
	return &CreateBulletinParams{
		HTTPClient: client,
	}
}

/*CreateBulletinParams contains all the parameters to send to the API endpoint
for the create bulletin operation typically these are written to a http.Request
*/
type CreateBulletinParams struct {

	/*Body
	  The reporting task configuration details.

	*/
	Body *models.BulletinEntity

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create bulletin params
func (o *CreateBulletinParams) WithTimeout(timeout time.Duration) *CreateBulletinParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create bulletin params
func (o *CreateBulletinParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create bulletin params
func (o *CreateBulletinParams) WithContext(ctx context.Context) *CreateBulletinParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create bulletin params
func (o *CreateBulletinParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create bulletin params
func (o *CreateBulletinParams) WithHTTPClient(client *http.Client) *CreateBulletinParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create bulletin params
func (o *CreateBulletinParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create bulletin params
func (o *CreateBulletinParams) WithBody(body *models.BulletinEntity) *CreateBulletinParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create bulletin params
func (o *CreateBulletinParams) SetBody(body *models.BulletinEntity) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBulletinParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
