// Code generated by go-swagger; DO NOT EDIT.

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetRegistryClientParams creates a new GetRegistryClientParams object
// with the default values initialized.
func NewGetRegistryClientParams() *GetRegistryClientParams {
	var ()
	return &GetRegistryClientParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetRegistryClientParamsWithTimeout creates a new GetRegistryClientParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetRegistryClientParamsWithTimeout(timeout time.Duration) *GetRegistryClientParams {
	var ()
	return &GetRegistryClientParams{

		timeout: timeout,
	}
}

// NewGetRegistryClientParamsWithContext creates a new GetRegistryClientParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetRegistryClientParamsWithContext(ctx context.Context) *GetRegistryClientParams {
	var ()
	return &GetRegistryClientParams{

		Context: ctx,
	}
}

// NewGetRegistryClientParamsWithHTTPClient creates a new GetRegistryClientParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetRegistryClientParamsWithHTTPClient(client *http.Client) *GetRegistryClientParams {
	var ()
	return &GetRegistryClientParams{
		HTTPClient: client,
	}
}

/*GetRegistryClientParams contains all the parameters to send to the API endpoint
for the get registry client operation typically these are written to a http.Request
*/
type GetRegistryClientParams struct {

	/*ID
	  The registry id.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get registry client params
func (o *GetRegistryClientParams) WithTimeout(timeout time.Duration) *GetRegistryClientParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get registry client params
func (o *GetRegistryClientParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get registry client params
func (o *GetRegistryClientParams) WithContext(ctx context.Context) *GetRegistryClientParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get registry client params
func (o *GetRegistryClientParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get registry client params
func (o *GetRegistryClientParams) WithHTTPClient(client *http.Client) *GetRegistryClientParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get registry client params
func (o *GetRegistryClientParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get registry client params
func (o *GetRegistryClientParams) WithID(id string) *GetRegistryClientParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get registry client params
func (o *GetRegistryClientParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetRegistryClientParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
