// Code generated by go-swagger; DO NOT EDIT.

package accesssaml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// CreateDownloadTokenSamlReader is a Reader for the CreateDownloadTokenSaml structure.
type CreateDownloadTokenSamlReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateDownloadTokenSamlReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCreateDownloadTokenSamlOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewCreateDownloadTokenSamlForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewCreateDownloadTokenSamlConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateDownloadTokenSamlInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateDownloadTokenSamlOK creates a CreateDownloadTokenSamlOK with default headers values
func NewCreateDownloadTokenSamlOK() *CreateDownloadTokenSamlOK {
	return &CreateDownloadTokenSamlOK{}
}

/*CreateDownloadTokenSamlOK handles this case with default header values.

successful operation
*/
type CreateDownloadTokenSamlOK struct {
	Payload string
}

func (o *CreateDownloadTokenSamlOK) Error() string {
	return fmt.Sprintf("[POST /access/saml/download-token][%d] createDownloadTokenSamlOK  %+v", 200, o.Payload)
}

func (o *CreateDownloadTokenSamlOK) GetPayload() string {
	return o.Payload
}

func (o *CreateDownloadTokenSamlOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateDownloadTokenSamlForbidden creates a CreateDownloadTokenSamlForbidden with default headers values
func NewCreateDownloadTokenSamlForbidden() *CreateDownloadTokenSamlForbidden {
	return &CreateDownloadTokenSamlForbidden{}
}

/*CreateDownloadTokenSamlForbidden handles this case with default header values.

Client is not authorized to make this request.
*/
type CreateDownloadTokenSamlForbidden struct {
}

func (o *CreateDownloadTokenSamlForbidden) Error() string {
	return fmt.Sprintf("[POST /access/saml/download-token][%d] createDownloadTokenSamlForbidden ", 403)
}

func (o *CreateDownloadTokenSamlForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDownloadTokenSamlConflict creates a CreateDownloadTokenSamlConflict with default headers values
func NewCreateDownloadTokenSamlConflict() *CreateDownloadTokenSamlConflict {
	return &CreateDownloadTokenSamlConflict{}
}

/*CreateDownloadTokenSamlConflict handles this case with default header values.

Unable to create the download token because NiFi is not in the appropriate state. (i.e. may not have any tokens to grant or be configured to support username/password login)
*/
type CreateDownloadTokenSamlConflict struct {
}

func (o *CreateDownloadTokenSamlConflict) Error() string {
	return fmt.Sprintf("[POST /access/saml/download-token][%d] createDownloadTokenSamlConflict ", 409)
}

func (o *CreateDownloadTokenSamlConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCreateDownloadTokenSamlInternalServerError creates a CreateDownloadTokenSamlInternalServerError with default headers values
func NewCreateDownloadTokenSamlInternalServerError() *CreateDownloadTokenSamlInternalServerError {
	return &CreateDownloadTokenSamlInternalServerError{}
}

/*CreateDownloadTokenSamlInternalServerError handles this case with default header values.

Unable to create download token because an unexpected error occurred.
*/
type CreateDownloadTokenSamlInternalServerError struct {
}

func (o *CreateDownloadTokenSamlInternalServerError) Error() string {
	return fmt.Sprintf("[POST /access/saml/download-token][%d] createDownloadTokenSamlInternalServerError ", 500)
}

func (o *CreateDownloadTokenSamlInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
