// Code generated by go-swagger; DO NOT EDIT.

package accesssaml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewKnoxLogoutSamlParams creates a new KnoxLogoutSamlParams object
// with the default values initialized.
func NewKnoxLogoutSamlParams() *KnoxLogoutSamlParams {

	return &KnoxLogoutSamlParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewKnoxLogoutSamlParamsWithTimeout creates a new KnoxLogoutSamlParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewKnoxLogoutSamlParamsWithTimeout(timeout time.Duration) *KnoxLogoutSamlParams {

	return &KnoxLogoutSamlParams{

		timeout: timeout,
	}
}

// NewKnoxLogoutSamlParamsWithContext creates a new KnoxLogoutSamlParams object
// with the default values initialized, and the ability to set a context for a request
func NewKnoxLogoutSamlParamsWithContext(ctx context.Context) *KnoxLogoutSamlParams {

	return &KnoxLogoutSamlParams{

		Context: ctx,
	}
}

// NewKnoxLogoutSamlParamsWithHTTPClient creates a new KnoxLogoutSamlParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewKnoxLogoutSamlParamsWithHTTPClient(client *http.Client) *KnoxLogoutSamlParams {

	return &KnoxLogoutSamlParams{
		HTTPClient: client,
	}
}

/*KnoxLogoutSamlParams contains all the parameters to send to the API endpoint
for the knox logout saml operation typically these are written to a http.Request
*/
type KnoxLogoutSamlParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the knox logout saml params
func (o *KnoxLogoutSamlParams) WithTimeout(timeout time.Duration) *KnoxLogoutSamlParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the knox logout saml params
func (o *KnoxLogoutSamlParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the knox logout saml params
func (o *KnoxLogoutSamlParams) WithContext(ctx context.Context) *KnoxLogoutSamlParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the knox logout saml params
func (o *KnoxLogoutSamlParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the knox logout saml params
func (o *KnoxLogoutSamlParams) WithHTTPClient(client *http.Client) *KnoxLogoutSamlParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the knox logout saml params
func (o *KnoxLogoutSamlParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *KnoxLogoutSamlParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
