// Code generated by go-swagger; DO NOT EDIT.

package accesssaml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// KnoxRequestSamlReader is a Reader for the KnoxRequestSaml structure.
type KnoxRequestSamlReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KnoxRequestSamlReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewKnoxRequestSamlDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewKnoxRequestSamlDefault creates a KnoxRequestSamlDefault with default headers values
func NewKnoxRequestSamlDefault(code int) *KnoxRequestSamlDefault {
	return &KnoxRequestSamlDefault{
		_statusCode: code,
	}
}

/*KnoxRequestSamlDefault handles this case with default header values.

successful operation
*/
type KnoxRequestSamlDefault struct {
	_statusCode int
}

// Code gets the status code for the knox request saml default response
func (o *KnoxRequestSamlDefault) Code() int {
	return o._statusCode
}

func (o *KnoxRequestSamlDefault) Error() string {
	return fmt.Sprintf("[GET /access/saml/knox/request][%d] knoxRequestSaml default ", o._statusCode)
}

func (o *KnoxRequestSamlDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
