// Code generated by go-swagger; DO NOT EDIT.

package accesssaml

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// KnoxCallbackSamlReader is a Reader for the KnoxCallbackSaml structure.
type KnoxCallbackSamlReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KnoxCallbackSamlReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	result := NewKnoxCallbackSamlDefault(response.Code())
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	if response.Code()/100 == 2 {
		return result, nil
	}
	return nil, result
}

// NewKnoxCallbackSamlDefault creates a KnoxCallbackSamlDefault with default headers values
func NewKnoxCallbackSamlDefault(code int) *KnoxCallbackSamlDefault {
	return &KnoxCallbackSamlDefault{
		_statusCode: code,
	}
}

/*KnoxCallbackSamlDefault handles this case with default header values.

successful operation
*/
type KnoxCallbackSamlDefault struct {
	_statusCode int
}

// Code gets the status code for the knox callback saml default response
func (o *KnoxCallbackSamlDefault) Code() int {
	return o._statusCode
}

func (o *KnoxCallbackSamlDefault) Error() string {
	return fmt.Sprintf("[GET /access/saml/knox/callback][%d] knoxCallbackSaml default ", o._statusCode)
}

func (o *KnoxCallbackSamlDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
