// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/bjornm82/go-swagger-nifi/models"
)

// NewUpdateAccessPolicyParams creates a new UpdateAccessPolicyParams object
// with the default values initialized.
func NewUpdateAccessPolicyParams() *UpdateAccessPolicyParams {
	var ()
	return &UpdateAccessPolicyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAccessPolicyParamsWithTimeout creates a new UpdateAccessPolicyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAccessPolicyParamsWithTimeout(timeout time.Duration) *UpdateAccessPolicyParams {
	var ()
	return &UpdateAccessPolicyParams{

		timeout: timeout,
	}
}

// NewUpdateAccessPolicyParamsWithContext creates a new UpdateAccessPolicyParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAccessPolicyParamsWithContext(ctx context.Context) *UpdateAccessPolicyParams {
	var ()
	return &UpdateAccessPolicyParams{

		Context: ctx,
	}
}

// NewUpdateAccessPolicyParamsWithHTTPClient creates a new UpdateAccessPolicyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAccessPolicyParamsWithHTTPClient(client *http.Client) *UpdateAccessPolicyParams {
	var ()
	return &UpdateAccessPolicyParams{
		HTTPClient: client,
	}
}

/*UpdateAccessPolicyParams contains all the parameters to send to the API endpoint
for the update access policy operation typically these are written to a http.Request
*/
type UpdateAccessPolicyParams struct {

	/*Body
	  The access policy configuration details.

	*/
	Body *models.AccessPolicyEntity
	/*ID
	  The access policy id.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update access policy params
func (o *UpdateAccessPolicyParams) WithTimeout(timeout time.Duration) *UpdateAccessPolicyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update access policy params
func (o *UpdateAccessPolicyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update access policy params
func (o *UpdateAccessPolicyParams) WithContext(ctx context.Context) *UpdateAccessPolicyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update access policy params
func (o *UpdateAccessPolicyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update access policy params
func (o *UpdateAccessPolicyParams) WithHTTPClient(client *http.Client) *UpdateAccessPolicyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update access policy params
func (o *UpdateAccessPolicyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update access policy params
func (o *UpdateAccessPolicyParams) WithBody(body *models.AccessPolicyEntity) *UpdateAccessPolicyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update access policy params
func (o *UpdateAccessPolicyParams) SetBody(body *models.AccessPolicyEntity) {
	o.Body = body
}

// WithID adds the id to the update access policy params
func (o *UpdateAccessPolicyParams) WithID(id string) *UpdateAccessPolicyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update access policy params
func (o *UpdateAccessPolicyParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAccessPolicyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
