// Code generated by go-swagger; DO NOT EDIT.

package process_groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetProcessorsParams creates a new GetProcessorsParams object
// with the default values initialized.
func NewGetProcessorsParams() *GetProcessorsParams {
	var (
		includeDescendantGroupsDefault = bool(false)
	)
	return &GetProcessorsParams{
		IncludeDescendantGroups: &includeDescendantGroupsDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetProcessorsParamsWithTimeout creates a new GetProcessorsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetProcessorsParamsWithTimeout(timeout time.Duration) *GetProcessorsParams {
	var (
		includeDescendantGroupsDefault = bool(false)
	)
	return &GetProcessorsParams{
		IncludeDescendantGroups: &includeDescendantGroupsDefault,

		timeout: timeout,
	}
}

// NewGetProcessorsParamsWithContext creates a new GetProcessorsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetProcessorsParamsWithContext(ctx context.Context) *GetProcessorsParams {
	var (
		includeDescendantGroupsDefault = bool(false)
	)
	return &GetProcessorsParams{
		IncludeDescendantGroups: &includeDescendantGroupsDefault,

		Context: ctx,
	}
}

// NewGetProcessorsParamsWithHTTPClient creates a new GetProcessorsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetProcessorsParamsWithHTTPClient(client *http.Client) *GetProcessorsParams {
	var (
		includeDescendantGroupsDefault = bool(false)
	)
	return &GetProcessorsParams{
		IncludeDescendantGroups: &includeDescendantGroupsDefault,
		HTTPClient:              client,
	}
}

/*GetProcessorsParams contains all the parameters to send to the API endpoint
for the get processors operation typically these are written to a http.Request
*/
type GetProcessorsParams struct {

	/*ID
	  The process group id.

	*/
	ID string
	/*IncludeDescendantGroups
	  Whether or not to include processors from descendant process groups

	*/
	IncludeDescendantGroups *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get processors params
func (o *GetProcessorsParams) WithTimeout(timeout time.Duration) *GetProcessorsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get processors params
func (o *GetProcessorsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get processors params
func (o *GetProcessorsParams) WithContext(ctx context.Context) *GetProcessorsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get processors params
func (o *GetProcessorsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get processors params
func (o *GetProcessorsParams) WithHTTPClient(client *http.Client) *GetProcessorsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get processors params
func (o *GetProcessorsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get processors params
func (o *GetProcessorsParams) WithID(id string) *GetProcessorsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get processors params
func (o *GetProcessorsParams) SetID(id string) {
	o.ID = id
}

// WithIncludeDescendantGroups adds the includeDescendantGroups to the get processors params
func (o *GetProcessorsParams) WithIncludeDescendantGroups(includeDescendantGroups *bool) *GetProcessorsParams {
	o.SetIncludeDescendantGroups(includeDescendantGroups)
	return o
}

// SetIncludeDescendantGroups adds the includeDescendantGroups to the get processors params
func (o *GetProcessorsParams) SetIncludeDescendantGroups(includeDescendantGroups *bool) {
	o.IncludeDescendantGroups = includeDescendantGroups
}

// WriteToRequest writes these params to a swagger request
func (o *GetProcessorsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.IncludeDescendantGroups != nil {

		// query param includeDescendantGroups
		var qrIncludeDescendantGroups bool
		if o.IncludeDescendantGroups != nil {
			qrIncludeDescendantGroups = *o.IncludeDescendantGroups
		}
		qIncludeDescendantGroups := swag.FormatBool(qrIncludeDescendantGroups)
		if qIncludeDescendantGroups != "" {
			if err := r.SetQueryParam("includeDescendantGroups", qIncludeDescendantGroups); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
