// Code generated by go-swagger; DO NOT EDIT.

package flowfile_queues

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/bjornm82/swagger-nifi/models"
)

// FlowfileQueuesRemoveDropRequestReader is a Reader for the FlowfileQueuesRemoveDropRequest structure.
type FlowfileQueuesRemoveDropRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FlowfileQueuesRemoveDropRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewFlowfileQueuesRemoveDropRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewFlowfileQueuesRemoveDropRequestBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewFlowfileQueuesRemoveDropRequestUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewFlowfileQueuesRemoveDropRequestForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewFlowfileQueuesRemoveDropRequestNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 409:
		result := NewFlowfileQueuesRemoveDropRequestConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewFlowfileQueuesRemoveDropRequestOK creates a FlowfileQueuesRemoveDropRequestOK with default headers values
func NewFlowfileQueuesRemoveDropRequestOK() *FlowfileQueuesRemoveDropRequestOK {
	return &FlowfileQueuesRemoveDropRequestOK{}
}

/*FlowfileQueuesRemoveDropRequestOK handles this case with default header values.

successful operation
*/
type FlowfileQueuesRemoveDropRequestOK struct {
	Payload *models.DropRequestEntity
}

func (o *FlowfileQueuesRemoveDropRequestOK) Error() string {
	return fmt.Sprintf("[DELETE /flowfile-queues/{id}/drop-requests/{drop-request-id}][%d] flowfileQueuesRemoveDropRequestOK  %+v", 200, o.Payload)
}

func (o *FlowfileQueuesRemoveDropRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DropRequestEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewFlowfileQueuesRemoveDropRequestBadRequest creates a FlowfileQueuesRemoveDropRequestBadRequest with default headers values
func NewFlowfileQueuesRemoveDropRequestBadRequest() *FlowfileQueuesRemoveDropRequestBadRequest {
	return &FlowfileQueuesRemoveDropRequestBadRequest{}
}

/*FlowfileQueuesRemoveDropRequestBadRequest handles this case with default header values.

NiFi was unable to complete the request because it was invalid. The request should not be retried without modification.
*/
type FlowfileQueuesRemoveDropRequestBadRequest struct {
}

func (o *FlowfileQueuesRemoveDropRequestBadRequest) Error() string {
	return fmt.Sprintf("[DELETE /flowfile-queues/{id}/drop-requests/{drop-request-id}][%d] flowfileQueuesRemoveDropRequestBadRequest ", 400)
}

func (o *FlowfileQueuesRemoveDropRequestBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewFlowfileQueuesRemoveDropRequestUnauthorized creates a FlowfileQueuesRemoveDropRequestUnauthorized with default headers values
func NewFlowfileQueuesRemoveDropRequestUnauthorized() *FlowfileQueuesRemoveDropRequestUnauthorized {
	return &FlowfileQueuesRemoveDropRequestUnauthorized{}
}

/*FlowfileQueuesRemoveDropRequestUnauthorized handles this case with default header values.

Client could not be authenticated.
*/
type FlowfileQueuesRemoveDropRequestUnauthorized struct {
}

func (o *FlowfileQueuesRemoveDropRequestUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /flowfile-queues/{id}/drop-requests/{drop-request-id}][%d] flowfileQueuesRemoveDropRequestUnauthorized ", 401)
}

func (o *FlowfileQueuesRemoveDropRequestUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewFlowfileQueuesRemoveDropRequestForbidden creates a FlowfileQueuesRemoveDropRequestForbidden with default headers values
func NewFlowfileQueuesRemoveDropRequestForbidden() *FlowfileQueuesRemoveDropRequestForbidden {
	return &FlowfileQueuesRemoveDropRequestForbidden{}
}

/*FlowfileQueuesRemoveDropRequestForbidden handles this case with default header values.

Client is not authorized to make this request.
*/
type FlowfileQueuesRemoveDropRequestForbidden struct {
}

func (o *FlowfileQueuesRemoveDropRequestForbidden) Error() string {
	return fmt.Sprintf("[DELETE /flowfile-queues/{id}/drop-requests/{drop-request-id}][%d] flowfileQueuesRemoveDropRequestForbidden ", 403)
}

func (o *FlowfileQueuesRemoveDropRequestForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewFlowfileQueuesRemoveDropRequestNotFound creates a FlowfileQueuesRemoveDropRequestNotFound with default headers values
func NewFlowfileQueuesRemoveDropRequestNotFound() *FlowfileQueuesRemoveDropRequestNotFound {
	return &FlowfileQueuesRemoveDropRequestNotFound{}
}

/*FlowfileQueuesRemoveDropRequestNotFound handles this case with default header values.

The specified resource could not be found.
*/
type FlowfileQueuesRemoveDropRequestNotFound struct {
}

func (o *FlowfileQueuesRemoveDropRequestNotFound) Error() string {
	return fmt.Sprintf("[DELETE /flowfile-queues/{id}/drop-requests/{drop-request-id}][%d] flowfileQueuesRemoveDropRequestNotFound ", 404)
}

func (o *FlowfileQueuesRemoveDropRequestNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewFlowfileQueuesRemoveDropRequestConflict creates a FlowfileQueuesRemoveDropRequestConflict with default headers values
func NewFlowfileQueuesRemoveDropRequestConflict() *FlowfileQueuesRemoveDropRequestConflict {
	return &FlowfileQueuesRemoveDropRequestConflict{}
}

/*FlowfileQueuesRemoveDropRequestConflict handles this case with default header values.

The request was valid but NiFi was not in the appropriate state to process it. Retrying the same request later may be successful.
*/
type FlowfileQueuesRemoveDropRequestConflict struct {
}

func (o *FlowfileQueuesRemoveDropRequestConflict) Error() string {
	return fmt.Sprintf("[DELETE /flowfile-queues/{id}/drop-requests/{drop-request-id}][%d] flowfileQueuesRemoveDropRequestConflict ", 409)
}

func (o *FlowfileQueuesRemoveDropRequestConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
