// Code generated by go-swagger; DO NOT EDIT.

package reporting_tasks

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewReportinTaskGetPropertyDescriptorParams creates a new ReportinTaskGetPropertyDescriptorParams object
// with the default values initialized.
func NewReportinTaskGetPropertyDescriptorParams() *ReportinTaskGetPropertyDescriptorParams {
	var ()
	return &ReportinTaskGetPropertyDescriptorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewReportinTaskGetPropertyDescriptorParamsWithTimeout creates a new ReportinTaskGetPropertyDescriptorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewReportinTaskGetPropertyDescriptorParamsWithTimeout(timeout time.Duration) *ReportinTaskGetPropertyDescriptorParams {
	var ()
	return &ReportinTaskGetPropertyDescriptorParams{

		timeout: timeout,
	}
}

// NewReportinTaskGetPropertyDescriptorParamsWithContext creates a new ReportinTaskGetPropertyDescriptorParams object
// with the default values initialized, and the ability to set a context for a request
func NewReportinTaskGetPropertyDescriptorParamsWithContext(ctx context.Context) *ReportinTaskGetPropertyDescriptorParams {
	var ()
	return &ReportinTaskGetPropertyDescriptorParams{

		Context: ctx,
	}
}

// NewReportinTaskGetPropertyDescriptorParamsWithHTTPClient creates a new ReportinTaskGetPropertyDescriptorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewReportinTaskGetPropertyDescriptorParamsWithHTTPClient(client *http.Client) *ReportinTaskGetPropertyDescriptorParams {
	var ()
	return &ReportinTaskGetPropertyDescriptorParams{
		HTTPClient: client,
	}
}

/*ReportinTaskGetPropertyDescriptorParams contains all the parameters to send to the API endpoint
for the reportin task get property descriptor operation typically these are written to a http.Request
*/
type ReportinTaskGetPropertyDescriptorParams struct {

	/*ID
	  The reporting task id.

	*/
	ID string
	/*PropertyName
	  The property name.

	*/
	PropertyName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the reportin task get property descriptor params
func (o *ReportinTaskGetPropertyDescriptorParams) WithTimeout(timeout time.Duration) *ReportinTaskGetPropertyDescriptorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the reportin task get property descriptor params
func (o *ReportinTaskGetPropertyDescriptorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the reportin task get property descriptor params
func (o *ReportinTaskGetPropertyDescriptorParams) WithContext(ctx context.Context) *ReportinTaskGetPropertyDescriptorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the reportin task get property descriptor params
func (o *ReportinTaskGetPropertyDescriptorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the reportin task get property descriptor params
func (o *ReportinTaskGetPropertyDescriptorParams) WithHTTPClient(client *http.Client) *ReportinTaskGetPropertyDescriptorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the reportin task get property descriptor params
func (o *ReportinTaskGetPropertyDescriptorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the reportin task get property descriptor params
func (o *ReportinTaskGetPropertyDescriptorParams) WithID(id string) *ReportinTaskGetPropertyDescriptorParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the reportin task get property descriptor params
func (o *ReportinTaskGetPropertyDescriptorParams) SetID(id string) {
	o.ID = id
}

// WithPropertyName adds the propertyName to the reportin task get property descriptor params
func (o *ReportinTaskGetPropertyDescriptorParams) WithPropertyName(propertyName string) *ReportinTaskGetPropertyDescriptorParams {
	o.SetPropertyName(propertyName)
	return o
}

// SetPropertyName adds the propertyName to the reportin task get property descriptor params
func (o *ReportinTaskGetPropertyDescriptorParams) SetPropertyName(propertyName string) {
	o.PropertyName = propertyName
}

// WriteToRequest writes these params to a swagger request
func (o *ReportinTaskGetPropertyDescriptorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// query param propertyName
	qrPropertyName := o.PropertyName
	qPropertyName := qrPropertyName
	if qPropertyName != "" {
		if err := r.SetQueryParam("propertyName", qPropertyName); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
