// Code generated by go-swagger; DO NOT EDIT.

package provenance

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSearchOptionsParams creates a new GetSearchOptionsParams object
// with the default values initialized.
func NewGetSearchOptionsParams() *GetSearchOptionsParams {

	return &GetSearchOptionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSearchOptionsParamsWithTimeout creates a new GetSearchOptionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSearchOptionsParamsWithTimeout(timeout time.Duration) *GetSearchOptionsParams {

	return &GetSearchOptionsParams{

		timeout: timeout,
	}
}

// NewGetSearchOptionsParamsWithContext creates a new GetSearchOptionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSearchOptionsParamsWithContext(ctx context.Context) *GetSearchOptionsParams {

	return &GetSearchOptionsParams{

		Context: ctx,
	}
}

// NewGetSearchOptionsParamsWithHTTPClient creates a new GetSearchOptionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSearchOptionsParamsWithHTTPClient(client *http.Client) *GetSearchOptionsParams {

	return &GetSearchOptionsParams{
		HTTPClient: client,
	}
}

/*GetSearchOptionsParams contains all the parameters to send to the API endpoint
for the get search options operation typically these are written to a http.Request
*/
type GetSearchOptionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get search options params
func (o *GetSearchOptionsParams) WithTimeout(timeout time.Duration) *GetSearchOptionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get search options params
func (o *GetSearchOptionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get search options params
func (o *GetSearchOptionsParams) WithContext(ctx context.Context) *GetSearchOptionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get search options params
func (o *GetSearchOptionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get search options params
func (o *GetSearchOptionsParams) WithHTTPClient(client *http.Client) *GetSearchOptionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get search options params
func (o *GetSearchOptionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetSearchOptionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
