// Code generated by go-swagger; DO NOT EDIT.

package parameter_contexts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteParameterContextParams creates a new DeleteParameterContextParams object
// with the default values initialized.
func NewDeleteParameterContextParams() *DeleteParameterContextParams {
	var (
		disconnectedNodeAcknowledgedDefault = bool(false)
	)
	return &DeleteParameterContextParams{
		DisconnectedNodeAcknowledged: &disconnectedNodeAcknowledgedDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteParameterContextParamsWithTimeout creates a new DeleteParameterContextParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteParameterContextParamsWithTimeout(timeout time.Duration) *DeleteParameterContextParams {
	var (
		disconnectedNodeAcknowledgedDefault = bool(false)
	)
	return &DeleteParameterContextParams{
		DisconnectedNodeAcknowledged: &disconnectedNodeAcknowledgedDefault,

		timeout: timeout,
	}
}

// NewDeleteParameterContextParamsWithContext creates a new DeleteParameterContextParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteParameterContextParamsWithContext(ctx context.Context) *DeleteParameterContextParams {
	var (
		disconnectedNodeAcknowledgedDefault = bool(false)
	)
	return &DeleteParameterContextParams{
		DisconnectedNodeAcknowledged: &disconnectedNodeAcknowledgedDefault,

		Context: ctx,
	}
}

// NewDeleteParameterContextParamsWithHTTPClient creates a new DeleteParameterContextParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteParameterContextParamsWithHTTPClient(client *http.Client) *DeleteParameterContextParams {
	var (
		disconnectedNodeAcknowledgedDefault = bool(false)
	)
	return &DeleteParameterContextParams{
		DisconnectedNodeAcknowledged: &disconnectedNodeAcknowledgedDefault,
		HTTPClient:                   client,
	}
}

/*DeleteParameterContextParams contains all the parameters to send to the API endpoint
for the delete parameter context operation typically these are written to a http.Request
*/
type DeleteParameterContextParams struct {

	/*ClientID
	  If the client id is not specified, a new one will be generated. This value (whether specified or generated) is included in the response.

	*/
	ClientID *string
	/*DisconnectedNodeAcknowledged
	  Acknowledges that this node is disconnected to allow for mutable requests to proceed.

	*/
	DisconnectedNodeAcknowledged *bool
	/*ID
	  The Parameter Context ID.

	*/
	ID string
	/*Version
	  The version is used to verify the client is working with the latest version of the flow.

	*/
	Version *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete parameter context params
func (o *DeleteParameterContextParams) WithTimeout(timeout time.Duration) *DeleteParameterContextParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete parameter context params
func (o *DeleteParameterContextParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete parameter context params
func (o *DeleteParameterContextParams) WithContext(ctx context.Context) *DeleteParameterContextParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete parameter context params
func (o *DeleteParameterContextParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete parameter context params
func (o *DeleteParameterContextParams) WithHTTPClient(client *http.Client) *DeleteParameterContextParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete parameter context params
func (o *DeleteParameterContextParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClientID adds the clientID to the delete parameter context params
func (o *DeleteParameterContextParams) WithClientID(clientID *string) *DeleteParameterContextParams {
	o.SetClientID(clientID)
	return o
}

// SetClientID adds the clientId to the delete parameter context params
func (o *DeleteParameterContextParams) SetClientID(clientID *string) {
	o.ClientID = clientID
}

// WithDisconnectedNodeAcknowledged adds the disconnectedNodeAcknowledged to the delete parameter context params
func (o *DeleteParameterContextParams) WithDisconnectedNodeAcknowledged(disconnectedNodeAcknowledged *bool) *DeleteParameterContextParams {
	o.SetDisconnectedNodeAcknowledged(disconnectedNodeAcknowledged)
	return o
}

// SetDisconnectedNodeAcknowledged adds the disconnectedNodeAcknowledged to the delete parameter context params
func (o *DeleteParameterContextParams) SetDisconnectedNodeAcknowledged(disconnectedNodeAcknowledged *bool) {
	o.DisconnectedNodeAcknowledged = disconnectedNodeAcknowledged
}

// WithID adds the id to the delete parameter context params
func (o *DeleteParameterContextParams) WithID(id string) *DeleteParameterContextParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete parameter context params
func (o *DeleteParameterContextParams) SetID(id string) {
	o.ID = id
}

// WithVersion adds the version to the delete parameter context params
func (o *DeleteParameterContextParams) WithVersion(version *string) *DeleteParameterContextParams {
	o.SetVersion(version)
	return o
}

// SetVersion adds the version to the delete parameter context params
func (o *DeleteParameterContextParams) SetVersion(version *string) {
	o.Version = version
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteParameterContextParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ClientID != nil {

		// query param clientId
		var qrClientID string
		if o.ClientID != nil {
			qrClientID = *o.ClientID
		}
		qClientID := qrClientID
		if qClientID != "" {
			if err := r.SetQueryParam("clientId", qClientID); err != nil {
				return err
			}
		}

	}

	if o.DisconnectedNodeAcknowledged != nil {

		// query param disconnectedNodeAcknowledged
		var qrDisconnectedNodeAcknowledged bool
		if o.DisconnectedNodeAcknowledged != nil {
			qrDisconnectedNodeAcknowledged = *o.DisconnectedNodeAcknowledged
		}
		qDisconnectedNodeAcknowledged := swag.FormatBool(qrDisconnectedNodeAcknowledged)
		if qDisconnectedNodeAcknowledged != "" {
			if err := r.SetQueryParam("disconnectedNodeAcknowledged", qDisconnectedNodeAcknowledged); err != nil {
				return err
			}
		}

	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Version != nil {

		// query param version
		var qrVersion string
		if o.Version != nil {
			qrVersion = *o.Version
		}
		qVersion := qrVersion
		if qVersion != "" {
			if err := r.SetQueryParam("version", qVersion); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
