// Code generated by go-swagger; DO NOT EDIT.

package parameter_contexts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteUpdateRequestParameterContextsParams creates a new DeleteUpdateRequestParameterContextsParams object
// with the default values initialized.
func NewDeleteUpdateRequestParameterContextsParams() *DeleteUpdateRequestParameterContextsParams {
	var (
		disconnectedNodeAcknowledgedDefault = bool(false)
	)
	return &DeleteUpdateRequestParameterContextsParams{
		DisconnectedNodeAcknowledged: &disconnectedNodeAcknowledgedDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteUpdateRequestParameterContextsParamsWithTimeout creates a new DeleteUpdateRequestParameterContextsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteUpdateRequestParameterContextsParamsWithTimeout(timeout time.Duration) *DeleteUpdateRequestParameterContextsParams {
	var (
		disconnectedNodeAcknowledgedDefault = bool(false)
	)
	return &DeleteUpdateRequestParameterContextsParams{
		DisconnectedNodeAcknowledged: &disconnectedNodeAcknowledgedDefault,

		timeout: timeout,
	}
}

// NewDeleteUpdateRequestParameterContextsParamsWithContext creates a new DeleteUpdateRequestParameterContextsParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteUpdateRequestParameterContextsParamsWithContext(ctx context.Context) *DeleteUpdateRequestParameterContextsParams {
	var (
		disconnectedNodeAcknowledgedDefault = bool(false)
	)
	return &DeleteUpdateRequestParameterContextsParams{
		DisconnectedNodeAcknowledged: &disconnectedNodeAcknowledgedDefault,

		Context: ctx,
	}
}

// NewDeleteUpdateRequestParameterContextsParamsWithHTTPClient creates a new DeleteUpdateRequestParameterContextsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteUpdateRequestParameterContextsParamsWithHTTPClient(client *http.Client) *DeleteUpdateRequestParameterContextsParams {
	var (
		disconnectedNodeAcknowledgedDefault = bool(false)
	)
	return &DeleteUpdateRequestParameterContextsParams{
		DisconnectedNodeAcknowledged: &disconnectedNodeAcknowledgedDefault,
		HTTPClient:                   client,
	}
}

/*DeleteUpdateRequestParameterContextsParams contains all the parameters to send to the API endpoint
for the delete update request parameter contexts operation typically these are written to a http.Request
*/
type DeleteUpdateRequestParameterContextsParams struct {

	/*ContextID
	  The ID of the ParameterContext

	*/
	ContextID string
	/*DisconnectedNodeAcknowledged
	  Acknowledges that this node is disconnected to allow for mutable requests to proceed.

	*/
	DisconnectedNodeAcknowledged *bool
	/*RequestID
	  The ID of the Update Request

	*/
	RequestID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) WithTimeout(timeout time.Duration) *DeleteUpdateRequestParameterContextsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) WithContext(ctx context.Context) *DeleteUpdateRequestParameterContextsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) WithHTTPClient(client *http.Client) *DeleteUpdateRequestParameterContextsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContextID adds the contextID to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) WithContextID(contextID string) *DeleteUpdateRequestParameterContextsParams {
	o.SetContextID(contextID)
	return o
}

// SetContextID adds the contextId to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) SetContextID(contextID string) {
	o.ContextID = contextID
}

// WithDisconnectedNodeAcknowledged adds the disconnectedNodeAcknowledged to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) WithDisconnectedNodeAcknowledged(disconnectedNodeAcknowledged *bool) *DeleteUpdateRequestParameterContextsParams {
	o.SetDisconnectedNodeAcknowledged(disconnectedNodeAcknowledged)
	return o
}

// SetDisconnectedNodeAcknowledged adds the disconnectedNodeAcknowledged to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) SetDisconnectedNodeAcknowledged(disconnectedNodeAcknowledged *bool) {
	o.DisconnectedNodeAcknowledged = disconnectedNodeAcknowledged
}

// WithRequestID adds the requestID to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) WithRequestID(requestID string) *DeleteUpdateRequestParameterContextsParams {
	o.SetRequestID(requestID)
	return o
}

// SetRequestID adds the requestId to the delete update request parameter contexts params
func (o *DeleteUpdateRequestParameterContextsParams) SetRequestID(requestID string) {
	o.RequestID = requestID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteUpdateRequestParameterContextsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param contextId
	if err := r.SetPathParam("contextId", o.ContextID); err != nil {
		return err
	}

	if o.DisconnectedNodeAcknowledged != nil {

		// query param disconnectedNodeAcknowledged
		var qrDisconnectedNodeAcknowledged bool
		if o.DisconnectedNodeAcknowledged != nil {
			qrDisconnectedNodeAcknowledged = *o.DisconnectedNodeAcknowledged
		}
		qDisconnectedNodeAcknowledged := swag.FormatBool(qrDisconnectedNodeAcknowledged)
		if qDisconnectedNodeAcknowledged != "" {
			if err := r.SetQueryParam("disconnectedNodeAcknowledged", qDisconnectedNodeAcknowledged); err != nil {
				return err
			}
		}

	}

	// path param requestId
	if err := r.SetPathParam("requestId", o.RequestID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
