// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjornm82/go-swagger-nifi/models"
)

// GetPropertyDescriptorProcessorsReader is a Reader for the GetPropertyDescriptorProcessors structure.
type GetPropertyDescriptorProcessorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPropertyDescriptorProcessorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPropertyDescriptorProcessorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetPropertyDescriptorProcessorsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetPropertyDescriptorProcessorsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetPropertyDescriptorProcessorsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetPropertyDescriptorProcessorsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetPropertyDescriptorProcessorsConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetPropertyDescriptorProcessorsOK creates a GetPropertyDescriptorProcessorsOK with default headers values
func NewGetPropertyDescriptorProcessorsOK() *GetPropertyDescriptorProcessorsOK {
	return &GetPropertyDescriptorProcessorsOK{}
}

/*GetPropertyDescriptorProcessorsOK handles this case with default header values.

successful operation
*/
type GetPropertyDescriptorProcessorsOK struct {
	Payload *models.PropertyDescriptorEntity
}

func (o *GetPropertyDescriptorProcessorsOK) Error() string {
	return fmt.Sprintf("[GET /processors/{id}/descriptors][%d] getPropertyDescriptorProcessorsOK  %+v", 200, o.Payload)
}

func (o *GetPropertyDescriptorProcessorsOK) GetPayload() *models.PropertyDescriptorEntity {
	return o.Payload
}

func (o *GetPropertyDescriptorProcessorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PropertyDescriptorEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetPropertyDescriptorProcessorsBadRequest creates a GetPropertyDescriptorProcessorsBadRequest with default headers values
func NewGetPropertyDescriptorProcessorsBadRequest() *GetPropertyDescriptorProcessorsBadRequest {
	return &GetPropertyDescriptorProcessorsBadRequest{}
}

/*GetPropertyDescriptorProcessorsBadRequest handles this case with default header values.

NiFi was unable to complete the request because it was invalid. The request should not be retried without modification.
*/
type GetPropertyDescriptorProcessorsBadRequest struct {
}

func (o *GetPropertyDescriptorProcessorsBadRequest) Error() string {
	return fmt.Sprintf("[GET /processors/{id}/descriptors][%d] getPropertyDescriptorProcessorsBadRequest ", 400)
}

func (o *GetPropertyDescriptorProcessorsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPropertyDescriptorProcessorsUnauthorized creates a GetPropertyDescriptorProcessorsUnauthorized with default headers values
func NewGetPropertyDescriptorProcessorsUnauthorized() *GetPropertyDescriptorProcessorsUnauthorized {
	return &GetPropertyDescriptorProcessorsUnauthorized{}
}

/*GetPropertyDescriptorProcessorsUnauthorized handles this case with default header values.

Client could not be authenticated.
*/
type GetPropertyDescriptorProcessorsUnauthorized struct {
}

func (o *GetPropertyDescriptorProcessorsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /processors/{id}/descriptors][%d] getPropertyDescriptorProcessorsUnauthorized ", 401)
}

func (o *GetPropertyDescriptorProcessorsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPropertyDescriptorProcessorsForbidden creates a GetPropertyDescriptorProcessorsForbidden with default headers values
func NewGetPropertyDescriptorProcessorsForbidden() *GetPropertyDescriptorProcessorsForbidden {
	return &GetPropertyDescriptorProcessorsForbidden{}
}

/*GetPropertyDescriptorProcessorsForbidden handles this case with default header values.

Client is not authorized to make this request.
*/
type GetPropertyDescriptorProcessorsForbidden struct {
}

func (o *GetPropertyDescriptorProcessorsForbidden) Error() string {
	return fmt.Sprintf("[GET /processors/{id}/descriptors][%d] getPropertyDescriptorProcessorsForbidden ", 403)
}

func (o *GetPropertyDescriptorProcessorsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPropertyDescriptorProcessorsNotFound creates a GetPropertyDescriptorProcessorsNotFound with default headers values
func NewGetPropertyDescriptorProcessorsNotFound() *GetPropertyDescriptorProcessorsNotFound {
	return &GetPropertyDescriptorProcessorsNotFound{}
}

/*GetPropertyDescriptorProcessorsNotFound handles this case with default header values.

The specified resource could not be found.
*/
type GetPropertyDescriptorProcessorsNotFound struct {
}

func (o *GetPropertyDescriptorProcessorsNotFound) Error() string {
	return fmt.Sprintf("[GET /processors/{id}/descriptors][%d] getPropertyDescriptorProcessorsNotFound ", 404)
}

func (o *GetPropertyDescriptorProcessorsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetPropertyDescriptorProcessorsConflict creates a GetPropertyDescriptorProcessorsConflict with default headers values
func NewGetPropertyDescriptorProcessorsConflict() *GetPropertyDescriptorProcessorsConflict {
	return &GetPropertyDescriptorProcessorsConflict{}
}

/*GetPropertyDescriptorProcessorsConflict handles this case with default header values.

The request was valid but NiFi was not in the appropriate state to process it. Retrying the same request later may be successful.
*/
type GetPropertyDescriptorProcessorsConflict struct {
}

func (o *GetPropertyDescriptorProcessorsConflict) Error() string {
	return fmt.Sprintf("[GET /processors/{id}/descriptors][%d] getPropertyDescriptorProcessorsConflict ", 409)
}

func (o *GetPropertyDescriptorProcessorsConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
