// Code generated by go-swagger; DO NOT EDIT.

package controller_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/bjornm82/go-swagger-nifi/models"
)

// NewUpdateControllerServiceReferencesParams creates a new UpdateControllerServiceReferencesParams object
// with the default values initialized.
func NewUpdateControllerServiceReferencesParams() *UpdateControllerServiceReferencesParams {
	var ()
	return &UpdateControllerServiceReferencesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateControllerServiceReferencesParamsWithTimeout creates a new UpdateControllerServiceReferencesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateControllerServiceReferencesParamsWithTimeout(timeout time.Duration) *UpdateControllerServiceReferencesParams {
	var ()
	return &UpdateControllerServiceReferencesParams{

		timeout: timeout,
	}
}

// NewUpdateControllerServiceReferencesParamsWithContext creates a new UpdateControllerServiceReferencesParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateControllerServiceReferencesParamsWithContext(ctx context.Context) *UpdateControllerServiceReferencesParams {
	var ()
	return &UpdateControllerServiceReferencesParams{

		Context: ctx,
	}
}

// NewUpdateControllerServiceReferencesParamsWithHTTPClient creates a new UpdateControllerServiceReferencesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateControllerServiceReferencesParamsWithHTTPClient(client *http.Client) *UpdateControllerServiceReferencesParams {
	var ()
	return &UpdateControllerServiceReferencesParams{
		HTTPClient: client,
	}
}

/*UpdateControllerServiceReferencesParams contains all the parameters to send to the API endpoint
for the update controller service references operation typically these are written to a http.Request
*/
type UpdateControllerServiceReferencesParams struct {

	/*Body
	  The controller service request update request.

	*/
	Body *models.UpdateControllerServiceReferenceRequestEntity
	/*ID
	  The controller service id.

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update controller service references params
func (o *UpdateControllerServiceReferencesParams) WithTimeout(timeout time.Duration) *UpdateControllerServiceReferencesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update controller service references params
func (o *UpdateControllerServiceReferencesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update controller service references params
func (o *UpdateControllerServiceReferencesParams) WithContext(ctx context.Context) *UpdateControllerServiceReferencesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update controller service references params
func (o *UpdateControllerServiceReferencesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update controller service references params
func (o *UpdateControllerServiceReferencesParams) WithHTTPClient(client *http.Client) *UpdateControllerServiceReferencesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update controller service references params
func (o *UpdateControllerServiceReferencesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update controller service references params
func (o *UpdateControllerServiceReferencesParams) WithBody(body *models.UpdateControllerServiceReferenceRequestEntity) *UpdateControllerServiceReferencesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update controller service references params
func (o *UpdateControllerServiceReferencesParams) SetBody(body *models.UpdateControllerServiceReferenceRequestEntity) {
	o.Body = body
}

// WithID adds the id to the update controller service references params
func (o *UpdateControllerServiceReferencesParams) WithID(id string) *UpdateControllerServiceReferencesParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update controller service references params
func (o *UpdateControllerServiceReferencesParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateControllerServiceReferencesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
