// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConnectionDiagnosticsDTO connection diagnostics d t o
//
// swagger:model ConnectionDiagnosticsDTO
type ConnectionDiagnosticsDTO struct {

	// Aggregate values for all nodes in the cluster, or for this instance if not clustered
	AggregateSnapshot *ConnectionDiagnosticsSnapshotDTO `json:"aggregateSnapshot,omitempty"`

	// Details about the connection
	Connection *ConnectionDTO `json:"connection,omitempty"`

	// A list of values for each node in the cluster, if clustered.
	NodeSnapshots []*ConnectionDiagnosticsSnapshotDTO `json:"nodeSnapshots"`
}

// Validate validates this connection diagnostics d t o
func (m *ConnectionDiagnosticsDTO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAggregateSnapshot(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConnection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNodeSnapshots(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConnectionDiagnosticsDTO) validateAggregateSnapshot(formats strfmt.Registry) error {

	if swag.IsZero(m.AggregateSnapshot) { // not required
		return nil
	}

	if m.AggregateSnapshot != nil {
		if err := m.AggregateSnapshot.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("aggregateSnapshot")
			}
			return err
		}
	}

	return nil
}

func (m *ConnectionDiagnosticsDTO) validateConnection(formats strfmt.Registry) error {

	if swag.IsZero(m.Connection) { // not required
		return nil
	}

	if m.Connection != nil {
		if err := m.Connection.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("connection")
			}
			return err
		}
	}

	return nil
}

func (m *ConnectionDiagnosticsDTO) validateNodeSnapshots(formats strfmt.Registry) error {

	if swag.IsZero(m.NodeSnapshots) { // not required
		return nil
	}

	for i := 0; i < len(m.NodeSnapshots); i++ {
		if swag.IsZero(m.NodeSnapshots[i]) { // not required
			continue
		}

		if m.NodeSnapshots[i] != nil {
			if err := m.NodeSnapshots[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("nodeSnapshots" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConnectionDiagnosticsDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnectionDiagnosticsDTO) UnmarshalBinary(b []byte) error {
	var res ConnectionDiagnosticsDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
