// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConnectionStatusSnapshotEntity connection status snapshot entity
//
// swagger:model ConnectionStatusSnapshotEntity
type ConnectionStatusSnapshotEntity struct {

	// Indicates whether the user can read a given resource.
	CanRead bool `json:"canRead,omitempty"`

	// connection status snapshot
	ConnectionStatusSnapshot *ConnectionStatusSnapshotDTO `json:"connectionStatusSnapshot,omitempty"`

	// The id of the connection.
	ID string `json:"id,omitempty"`
}

// Validate validates this connection status snapshot entity
func (m *ConnectionStatusSnapshotEntity) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateConnectionStatusSnapshot(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConnectionStatusSnapshotEntity) validateConnectionStatusSnapshot(formats strfmt.Registry) error {

	if swag.IsZero(m.ConnectionStatusSnapshot) { // not required
		return nil
	}

	if m.ConnectionStatusSnapshot != nil {
		if err := m.ConnectionStatusSnapshot.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("connectionStatusSnapshot")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConnectionStatusSnapshotEntity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConnectionStatusSnapshotEntity) UnmarshalBinary(b []byte) error {
	var res ConnectionStatusSnapshotEntity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
