// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Permissions permissions
//
// swagger:model Permissions
type Permissions struct {

	// Indicates whether the user can delete a given resource.
	// Read Only: true
	CanDelete *bool `json:"canDelete,omitempty"`

	// Indicates whether the user can read a given resource.
	// Read Only: true
	CanRead *bool `json:"canRead,omitempty"`

	// Indicates whether the user can write a given resource.
	// Read Only: true
	CanWrite *bool `json:"canWrite,omitempty"`
}

// Validate validates this permissions
func (m *Permissions) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Permissions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Permissions) UnmarshalBinary(b []byte) error {
	var res Permissions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
