// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ResourceDTO resource d t o
//
// swagger:model ResourceDTO
type ResourceDTO struct {

	// The identifier of the resource.
	Identifier string `json:"identifier,omitempty"`

	// The name of the resource.
	Name string `json:"name,omitempty"`
}

// Validate validates this resource d t o
func (m *ResourceDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceDTO) UnmarshalBinary(b []byte) error {
	var res ResourceDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
