// Code generated by go-swagger; DO NOT EDIT.

package access

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/bjornm82/go-swagger-nifi/models"
)

// GetLoginConfigAccessReader is a Reader for the GetLoginConfigAccess structure.
type GetLoginConfigAccessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLoginConfigAccessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLoginConfigAccessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetLoginConfigAccessOK creates a GetLoginConfigAccessOK with default headers values
func NewGetLoginConfigAccessOK() *GetLoginConfigAccessOK {
	return &GetLoginConfigAccessOK{}
}

/*GetLoginConfigAccessOK handles this case with default header values.

successful operation
*/
type GetLoginConfigAccessOK struct {
	Payload *models.AccessConfigurationEntity
}

func (o *GetLoginConfigAccessOK) Error() string {
	return fmt.Sprintf("[GET /access/config][%d] getLoginConfigAccessOK  %+v", 200, o.Payload)
}

func (o *GetLoginConfigAccessOK) GetPayload() *models.AccessConfigurationEntity {
	return o.Payload
}

func (o *GetLoginConfigAccessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccessConfigurationEntity)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
